In [7]:
import pandas


In [8]:
import numpy as np

arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
import numpy as np

arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr[8]

8

In [15]:
arr[0:5] = 50
arr

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10])

In [20]:
arr = np.arange(1,11)
arr
n = arr[0:5]
n
n[:]=99
n
arr


array([99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr2 = np.random.randint(2,50,(3,3))
arr2


array([[ 4, 21, 33],
       [16, 38, 19],
       [24, 23,  8]])

In [30]:
arr2[2,2]

8

In [33]:
arr2[:2,1:]

array([[21, 33],
       [38, 19]])

In [39]:
arr =np.arange(1,11)
arr
arr>4
bool_arr = arr>4
arr[bool_arr]
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [44]:
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

total_rolls_over_two = len(dice_rolls[dice_rolls>2])
total_rolls_over_two

19

In [52]:
arr
arr + 2
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr * arr
arr

arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [67]:
arr/arr
arr = arr-1
arr



C:\Users\huawe\AppData\Local\Temp\ipykernel_20284\405525155.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([-6, -5, -4, -3, -2, -1,  0,  1,  2,  3])

In [68]:
arr

array([-6, -5, -4, -3, -2, -1,  0,  1,  2,  3])

In [70]:
1/arr

C:\Users\huawe\AppData\Local\Temp\ipykernel_20284\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([-0.16666667, -0.2       , -0.25      , -0.33333333, -0.5       ,
       -1.        ,         inf,  1.        ,  0.5       ,  0.33333333])

In [77]:
arr
arr = np.arange(1,10)
arr
np.sqrt(arr)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr.sum(axis=0)

45

In [80]:
import numpy as np
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])
account_total = account_transactions.sum()
account_total

2720

In [3]:
import numpy as np
numbers1 = np.random.randint(10,100,6)
print(numbers1)
result = numbers1 % 2 == 0
result
print(numbers1[result])

[50 78 81 99 45 81]
[50 78]


In [8]:
dir(np.lcm)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__name__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'accumulate',
 'at',
 'identity',
 'nargs',
 'nin',
 'nout',
 'ntypes',
 'outer',
 'reduce',
 'reduceat',
 'signature',
 'types']

In [21]:
np.lcm.reduce(np.arange(1,20))

232792560

In [37]:
x=np.arange(1,21)
x
np.math.lcm(1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20)

232792560

In [38]:
import numpy as np

arr = np.arange(0,11)
arr.dtype

dtype('int32')

In [39]:
import numpy as np

arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [42]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [43]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [44]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [45]:
help(np.log)

Help on ufunc:

log = <ufunc 'log'>
    log(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Natural logarithm, element-wise.
    
    The natural logarithm `log` is the inverse of the exponential function,
    so that `log(exp(x)) = x`. The natural logarithm is logarithm in base
    `e`.
    
    Parameters
    ----------
    x : array_like
        Input value.
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, t

In [47]:
np.log([8,2])

array([2.07944154, 0.69314718])

In [58]:
a = np.arange(5,25)
a.var()
a.mean()
a.std()
x = a.reshape(2,2,5)
x

array([[[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])

In [64]:
x.sum(axis=1)
x.sum(axis=2)
x

array([[[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])

In [74]:
def print_full_name(first, last):
    print("Hello",first,last,"! You just delved into python.")

if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)
        
# print_full_name("Serdar","Can")


serdar
can
Hello serdar can ! You just delved into python.


In [76]:
import numpy as np
np.zeros(10,dtype="f")
# arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [79]:
arr = np.arange(1,11)
0/arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [80]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [81]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [83]:
arr = np.ones(10)
arr[:] = 5
arr


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [86]:
arr = np.ones(10)+4
arr



array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [88]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [89]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [90]:
arr = np.arange(0,9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [92]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [93]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [95]:
np.random.rand(1)

array([0.48450802])

In [97]:
np.random.randn(25)

array([-0.33212833,  0.05258348, -0.16943805, -1.93711966, -0.27640486,
        0.01527175,  1.47141215, -1.22778965, -0.89527717, -1.59313767,
        0.35846839, -0.66072389,  1.80817855,  0.31975913,  1.70028005,
       -1.40545038,  0.55650269,  0.58345469, -1.90282398,  0.36364642,
       -0.28985591,  1.36027166, -1.4456509 , -1.05457985,  1.22975664])

In [106]:
arr = np.arange(1,101)
arr.ndim

1

In [113]:
arr = np.arange(1,101)/100
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [117]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [118]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [124]:
mat.base[13:25].reshape(4,3)

array([[14, 15, 16],
       [17, 18, 19],
       [20, 21, 22],
       [23, 24, 25]])

In [126]:
mat[2:,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [130]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [132]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [134]:
mat[4]

array([21, 22, 23, 24, 25])

In [138]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [140]:
mat.std()

7.211102550927978

In [141]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [142]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])